export const FETCH_NOTE_REQUEST = 'FETCH_NOTE_REQUEST';
export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
export const FETCH_NOTE_FAIL = 'FETCH_NOTE_FAIL';
export const SAVE_NOTE_TO_STATE = 'SAVE_NOTE_TO_STATE';
export const SAVE_NOTE_TO_SERVER_REQUEST = 'SAVE_NOTE_TO_SERVER_REQUEST';
export const SAVE_NOTE_TO_SERVER_SUCCESS = 'SAVE_NOTE_TO_SERVER_SUCCESS';
export const SAVE_NOTE_TO_SERVER_FAIL = 'SAVE_NOTE_TO_SERVER_FAIL';
export const DELETE_THIS_NOTE = 'DELETE_THIS_NOTE';
